### ISSUE TITLE
Name - wouldn't Translation Manager be more accurate? 👀

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/language-manager#5]
I mean... 
- we don't let the admin manage languages... so why is it called "_language manager_"?
- we let the admin manage translations... soo.. why not call it "_translation manager_"?

Is it too late for that? 👀🤷‍♂️

**Comment by promatik** [comment]
Added https://github.com/Laravel-Backpack/language-manager/pull/7 for this 🙌
